CREATE TABLE noteful_notes (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_id INT REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    note_title TEXT NOT NULL,
    note_content TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
)